config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :posts do
  	resources :comments
  end
  root 'posts#index'

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.present?  
      can :read, :all
      can :manage, Post, user_id: user.id
      can :manage, Comment, Post:{ user: {id: user.id } }
      if user.admin?  
        can :manage, :all
      end
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts
  has_many :comments
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_omniauth(access_token)
      data = access_token.info
      user = User.where(email: data['email']).first
      unless user
           user = User.create(email: data['email'], password: Devise.friendly_token[0,20])
      end
      user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :find_post
	before_action :find_comment, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def create
		@comment = @post.comments.create(comment_params)
		@comment.user_id = current_user.id

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @comment.update(comment_params)
			redirect_to post_path(@post)
		else 
			render 'new'
		end
	end

	def destroy
		@comment.destroy
		redirect_to post_path(@post)
	end


	private

	def comment_params

		params.require(:comment).permit(:content)
	end

	def find_post
		@post = Post.find(params[:post_id])
	end

	def find_comment
		@comment = @post.comments.find(params[:id])
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts =  Post.all.order("created_at DESC").page(params[:page]).per(9)
	end

	def new
		@post = current_user.posts.build
	end


	def show
		
	end


	def edit
	end

	def update

		if @post.update(post_params)
			redirect_to post_path
		else 
			render 'edit'
		end

	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	private

		def post_params
			params.require(:post).permit(:title, :description)
		end

		def find_post

			@post = Post.find(params[:id])
		end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: 'Google') if is_navigational_format?
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
	<p class="comment-content"><%= comment.content %> </p>
	<p class="comment-posted-by">Commented by <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> </p>
	<div class="links">
		<% if user_signed_in? %>


				<% if current_user.admin %>
					<%= link_to "Edit", edit_post_comment_path(comment.post, comment) %>
					<%= link_to "Delete", post_comment_path(comment.post, comment), method: :delete, data: {comfirm: "Are you sure?"} %>
				<% else %>
					<% if comment.user_id == current_user.id %>
						<%= link_to "Edit", edit_post_comment_path(comment.post, comment) %>
						<%= link_to "Delete", post_comment_path(comment.post, comment), method: :delete, data: {comfirm: "Are you sure?"} %>


					<% end %>
				

				<% end %>
							
			
		<% end %>
	</div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>

	<%= f.input :content, label: "Comment" %>
	<%= f.button :submit, :class =>"btn-custom" %>

<% end %>

app/views/comments/edit.html.erb
<h1> Edit Comments </h1>

<%= simple_form_for ([@post, @comment]) do |f| %>
	<%= f.input :content, label: "Comment" %>
	<%= f.button :submit %>
<% end %> 

app/views/layouts/_footer.html.erb
<footer class="page-footer">

  <div class="container-fluid text-center text-md-left">

    <div class="row">

      <div class="col-md-6 mt-md-0 mt-3">

		<div class="paginate-pos">
      <% if user_signed_in? %>
		   

      <% end %>
		</div>

      </div>

      <hr class="clearfix w-100 d-md-none pb-3">


  </div>



  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a> Aidos </a>
  </div>


</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BulletinTraining</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Post Board" , root_path, class:'navbar-brand'%>
        </div>

        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li> <%= link_to "New Post", new_post_path %>  </li>
            <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li> <%=  link_to "Log in", new_user_session_path %> </li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
        </ul>
        <% if user_signed_in? %>
          <p class="navbar-right navbar-text nvabar"> <%= current_user.email %></p>
        <% end %>
      </div>
    </div>
    <div class="container">
      <p class="notice"><%= flash.now[notice] %></p>
      <p class="alert"><%= flash.now[alert] %></p>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>  
  </body>
</html>

<script>

<% if @post != nil %>
    post_id = <%= @post.id %>
<% else %>
    post_id = 0
<% end %>
    view_ip = '<%= request.remote_ip %>'

</script>

<% if @post != nil %>
<script type="text/javascript">
  
  scrollLocation = 0;
  scrollPercent = 0;
  x_pos = null;
  y_pos = null;

  ad_title = document.title;
  ad_url = window.location.href;

  console.log(post_id);
  console.log(view_ip);
  console.log(ad_url);
  console.log(ad_title);

  startTime = new Date();
  endTime = null;
  timeTable = new Array();
  scrollTable = new Array();
  btn_urls = new Array();
  btn_texts = new Array();

  currentHeight = screen.height;

  currentWidth = screen.width;

  var body = document.body;
    var html = document.documentElement;
  var height = Math.max(
    window.innerHeight
  );

  maxHeight = currentHeight + height;
  downHeight = height;

  console.log('currentHeight: ' + currentHeight, 'currentWidth: ' + currentWidth, 'maxHeight: ' + maxHeight);

  var buttons = document.getElementsByTagName("a");
  for (var i =0; i< buttons.length; i++){
    buttons[i].setAttribute("onclick", "mouseClick(this.id)");  
    buttons[i].id = i;
    if (buttons[i].firstElementChild != null) {
      if(buttons[i].firstElementChild.tagName == 'IMG'){
        btn_urls[i] = buttons[i].firstElementChild.getAttribute('src');
      }
      else {
        btn_texts[i] = buttons[i].innerText;
      }
    }
    else {
        btn_texts[i] = buttons[i].innerText;
    }

  };
  console.log(btn_urls)

  function mouseClick(clicked_btn){
      x_pos = event.clientX;
      y_pos = event.clientY;
      console.log('X:' + x_pos, 'Y: ' + y_pos, 'BTN: ' + btn_urls[clicked_btn] + btn_texts[clicked_btn]);

    navigator.sendBeacon(
      "http://localhost:8888/api/v1/articles/new?id="+15+";title="+ad_title+";url="+ad_url+";maxpos="+(height+300)
      );


    for (var i =0; i< timeTable.length; i++) 
    {
      navigator.sendBeacon("http://localhost:8888/api/v1/articles/"+15+"/scrolls/new?scroll_pos="+scrollTable[i]+";scroll_dur="+timeTable[i]);
    };

    navigator.sendBeacon(
      "http://localhost:8888/api/v1/articles/"+15+"/clicks/new?click_x="+x_pos+";click_y="+y_pos+";btn_url="+btn_urls[clicked_btn]+";btn_text="+btn_texts[clicked_btn]+";view_ip="+123
      );

  };

  window.addEventListener('scroll', function () {

    if(window.scrollY > scrollLocation) {
      scrollLocation = window.scrollY;
      if((scrollLocation +screen.height) > currentHeight) { //checks if the user scrolled for screen.height
        downHeight = window.scrollY;
        endTime = new Date(); // when user scrolls for screen.height gets new date at that point
        result = endTime - startTime; // gets the difference of startDate and screen.height -> endDate
        startTime = endTime; // makes starDate as last endDate
          if(scrollLocation + screen.height > height) {
                scrollTable.push(parseInt(100));
            }
            else{
            scrollTable.push(parseInt((window.scrollY + screen.height)/height*100));
            }
          timeTable.push(result/1000); //inserts the differences of dates
        currentHeight = currentHeight + screen.height;
      }
    }   
    else if(window.scrollY < scrollLocation){
      scrollLocation = window.scrollY;
      currentHeight = scrollLocation;
      if((scrollLocation + screen.height) < downHeight) {
        endTime = new Date();
        result = endTime - startTime;
        startTime = endTime;
        downHeight = downHeight - screen.height;
        scrollTable.push(parseInt((window.scrollY + screen.height)/height*100));
        timeTable.push(result/1000);
      }
    } 
  });

  window.addEventListener('unload', function(){

    navigator.sendBeacon(
      "http://localhost:8888/api/v1/articles/new?id="+15+";title="+ad_title+";url="+ad_url+";maxpos="+(height + 300)
      );

    for (var i =0; i< timeTable.length; i++) 
    {
      navigator.sendBeacon("http://localhost:8888/api/v1/articles/"+15+"/scrolls/new?scroll_pos="+scrollTable[i]+";scroll_dur="+timeTable[i]);
    };

    navigator.sendBeacon(
      "http://localhost:8888/api/v1/articles/"+15+"/clicks/new?click_x=null;click_y=null;btn_url=undefined;btn_text=undefined;view_ip="+123
    );
  });

</script>

<% end %>

app/views/posts/_form.html.erb
<%= simple_form_for @post do|f| %>

	<%= f.input :title, label: "Post Title" %>
	<%= f.input :description  %>
	<%= f.button :submit %>

<% end %>

app/views/posts/edit.html.erb
<h1> Edit </h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<div class="col-md-4">
		<div class="message">
			<h2 class="message-title"> <%= post.title %> </h2>
			<% if can? :read , @post %>
				<%= link_to "View Post", post_path(post), class: "btn-custom" %>
			<% else %>
				<p style="color: white; font-size: 10px;"> Pls Sign in to read the post</p>
			<% end %>
		</div>
	</div>
<% end %>
 <br>
 <br>

app/views/posts/new.html.erb
<div class="col-md-8 col-md-offset-2">
	<h1> New Post </h1>

	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="col-md-8 col-md-offset-2">
	<div class="message-show">
		<h2> <%= @post.title %> </h2>
		<p class="message-posted-by"> Posted by <%= @post.user.email %> <%= time_ago_in_words(@post.created_at) %></p>

		<p class="message-desc"> <%= @post.description %> </p>



		<h3> Comments </h3>

		<%= render @post.comments %>

		<h3 class="reply-to-msg"> Reply to a Post</h3>

		<%= render 'comments/form' %>

		<div class="links btn-group">

			<%= link_to "Back" , root_path , class:"btn btn-default" %>
			<% if user_signed_in?%>
				<% if can? :manage, @post %>
					<%= link_to "Edit" , edit_post_path(@post), class:"btn btn-default" %>
					<%= link_to "Delete" , post_path(@post), method: :delete, data: {confirm: "Are you sure?"} , class:"btn btn-default" %>
				<% end %>
			<% end %>
		</div>	
	</div>	
</div>